# Generated by Django 2.2 on 2020-02-09 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnaboard',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='qna_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
