# Generated by Django 3.0.2 on 2020-02-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_auto_20200214_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='is_valid_date',
            field=models.BooleanField(default=False),
        ),
    ]
