# Generated by Django 3.0.2 on 2020-02-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_careerboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerboard',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
