# Generated by Django 3.0.2 on 2020-02-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_qnaboard_like'),
        ('Board', '0002_auto_20200210_0320'),
    ]

    operations = [
    ]
