# Generated by Django 3.0.2 on 2020-02-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200222_1605'),
        ('board', '0003_auto_20200222_1907'),
    ]

    operations = [
    ]
