# Generated by Django 3.0.2 on 2020-02-22 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0004_merge_20200222_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('L', '강의자료'), ('A', '과제')], max_length=1)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='board.Session')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='score',
            old_name='scores',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='score_types',
            new_name='score_type',
        ),
        migrations.DeleteModel(
            name='LectureBoard',
        ),
        migrations.AddField(
            model_name='submission',
            name='scores',
            field=models.ManyToManyField(blank=True, related_name='_submission_scores_+', to='board.Score'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
