# Generated by Django 3.0.2 on 2020-01-31 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0004_qnaboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuitBoard',
            fields=[
                ('board_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Board.Board')),
                ('purpose', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Board.board',),
        ),
    ]
