# Generated by Django 3.0.2 on 2020-02-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200223_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='score_types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
