# Generated by Django 3.0.2 on 2020-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20200223_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
