# Generated by Django 3.0.2 on 2020-02-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_sessioncomment_submissioncomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerboard',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='noticeboard',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='noticeboardcomment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='qnaboard',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='qnaboardcomment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='sessioncomment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='studyboard',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='studyboardcomment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='submissioncomment',
            options={'ordering': ['-pub_date']},
        ),
    ]
