# Generated by Django 3.0.2 on 2020-02-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20200225_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaboardcomment',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_comments', to='board.QnABoard'),
        ),
        migrations.AlterField(
            model_name='qnaboardcomment',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomments', to='board.QnABoardComment'),
        ),
    ]
