# Generated by Django 3.0.2 on 2020-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20200225_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
