# Generated by Django 3.0.2 on 2020-02-28 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0012_submission_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerboard',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='career_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
