# Generated by Django 3.0.2 on 2020-02-06 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0012_auto_20200204_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyboard',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='study_scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
