# Generated by Django 3.0.2 on 2020-02-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20200228_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticeboardcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='qnaboardcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sessioncomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studyboardcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='submissioncomment',
            options={},
        ),
    ]
