# Generated by Django 3.0.2 on 2020-02-07 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0013_studyboard_scrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyboard',
            name='scrap',
        ),
        migrations.AddField(
            model_name='board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='board_scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
