# Generated by Django 3.0.2 on 2020-02-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20200229_0221'),
        ('board', '0014_auto_20200229_0250'),
    ]

    operations = [
    ]
