# Generated by Django 3.0.2 on 2020-02-29 04:38

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_merge_20200229_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=board.models.get_file_path)),
            ],
        ),
        migrations.DeleteModel(
            name='GenericImage',
        ),
    ]
