# Generated by Django 3.0.2 on 2020-02-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_studygroup_studygroup_user'),
        ('Board', '0015_auto_20200207_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup_connection',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studygroup_connection',
            name='participant',
        ),
        migrations.AlterField(
            model_name='studyboard',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.StudyGroup'),
        ),
        migrations.DeleteModel(
            name='StudyGroup',
        ),
        migrations.DeleteModel(
            name='StudyGroup_connection',
        ),
    ]
