# Generated by Django 3.0.2 on 2020-02-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_auto_20200229_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='start_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
