# Generated by Django 3.0.2 on 2020-03-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_session_start_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncomment',
            name='is_grader',
            field=models.BooleanField(default=False),
        ),
    ]
