# Generated by Django 3.0.2 on 2020-02-03 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='study',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='study_group', to='account.StudyGroup'),
        ),
    ]
