# Generated by Django 3.0.2 on 2020-02-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='study',
        ),
        migrations.DeleteModel(
            name='StudyGroup',
        ),
    ]
