# Generated by Django 3.0.2 on 2020-02-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_studygroup_studygroup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
