# Generated by Django 3.0.2 on 2020-02-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_mentoring_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='study',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_group', to='account.StudyGroup'),
        ),
    ]
