# Generated by Django 2.2.7 on 2020-02-03 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=300)),
                ('major', models.CharField(max_length=300)),
                ('e_mail', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('belong_to_join', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_answer', to='JoinForm.JoinForm')),
                ('belong_to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='JoinForm.Question')),
            ],
        ),
    ]
