# Generated by Django 3.0.2 on 2020-02-08 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=300)),
                ('birth', models.DateField()),
                ('sex', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=100)),
                ('e_mail', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('score', models.FloatField(default=0.0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('joinform_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='join_evaluation', to='Admission.JoinForm')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('joinform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_answer', to='Admission.JoinForm')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='Admission.Question')),
            ],
        ),
    ]
