# Generated by Django 3.0.2 on 2020-02-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinform',
            name='start_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='joinform_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='join_answer', to='Admission.JoinForm'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='Admission.Question'),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='e_mail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='major',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='phone_number',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='sex',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
