# Generated by Django 2.2 on 2020-02-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinform',
            name='e_mail',
        ),
        migrations.AddField(
            model_name='joinform',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='joinform',
            name='student_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='major',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
