# Generated by Django 3.0.2 on 2020-02-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0002_auto_20200210_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinform',
            old_name='password',
            new_name='pw',
        ),
    ]
