# Generated by Django 3.0.2 on 2020-02-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20200222_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', '합격'), ('R', '심사중'), ('F', '불합격')], default='R', max_length=1),
        ),
    ]
