# Generated by Django 3.0.2 on 2020-02-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0002_auto_20200209_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinform',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joinform',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
