# Generated by Django 3.0.2 on 2020-02-11 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0002_auto_20200211_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinform',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joinform',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
