# Generated by Django 3.0.2 on 2020-02-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20200222_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('R', '심사중'), ('F', '불합격'), ('P', '합격')], default='R', max_length=1),
        ),
    ]
