# Generated by Django 3.0.2 on 2020-02-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_auto_20200223_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='applicationform_id',
            new_name='application_id',
        ),
    ]
