# Generated by Django 3.0.2 on 2020-02-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_auto_20200224_0104'),
        ('admission', '0004_auto_20200223_2320'),
    ]

    operations = [
    ]
