# Generated by Django 3.0.2 on 2020-02-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_merge_20200224_1544'),
        ('admission', '0003_auto_20200222_2334'),
    ]

    operations = [
    ]
