# Generated by Django 3.0.2 on 2020-02-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20200224_1715'),
        ('admission', '0007_merge_20200224_1558'),
    ]

    operations = [
    ]
