# Generated by Django 3.0.2 on 2020-02-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_merge_20200224_2151'),
        ('admission', '0007_merge_20200224_2114'),
    ]

    operations = [
    ]
