# Generated by Django 3.0.2 on 2020-02-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Board', '0013_studyboard_scrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.ManyToManyField(blank=True, related_name='Board_hashtag', to='Board.Board')),
            ],
        ),
    ]
