# Generated by Django 3.0.2 on 2020-02-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
    ]
