# Generated by Django 2.2 on 2020-02-11 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0002_auto_20200211_2134'),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='career_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calender',
            name='notice_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='calender', to='Board.NoticeBoard'),
        ),
    ]
