# Generated by Django 3.0.2 on 2020-02-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200213_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='contents',
            field=models.TextField(),
        ),
    ]
