# Generated by Django 3.0.2 on 2020-02-11 16:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200211_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='link',
            field=models.URLField(),
        ),
    ]
