# Generated by Django 3.0.2 on 2020-02-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0003_noticeboard_is_valid_date'),
        ('Main', '0002_auto_20200214_0411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calender',
            new_name='Calendar',
        ),
    ]
