# Generated by Django 3.0.2 on 2020-02-13 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_auto_20200213_0020'),
        ('Main', '0003_auto_20200214_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='notice_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calender', to='Board.NoticeBoard'),
        ),
    ]
