# Generated by Django 3.0.2 on 2020-02-11 16:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20200212_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
