# Generated by Django 3.0.2 on 2020-02-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupuser',
            options={'ordering': ('group_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together={('user_id', 'group_id')},
        ),
    ]
