# Generated by Django 3.0.2 on 2020-02-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='img',
            field=models.ImageField(default='../static/images/default_group_image.png', upload_to='images/'),
        ),
    ]
