# Generated by Django 3.0.2 on 2020-03-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200223_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sns_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
