# Generated by Django 3.0.2 on 2020-02-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studygroup_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='img',
            field=models.ImageField(default='../static/images/defaut_group_image.png', upload_to='images/'),
        ),
    ]
